targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: true

builders:
  built_value:
    target: ":built_value_generator"
    import: "package:built_value_generator/builder.dart"
    builder_factories: ["builtValue"]
    build_extensions: {".dart": [".built_value.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    defaults:
      options:
        run_only_if_triggered: true

triggers:
  built_value_generator:built_value:
    - import built_value/built_value.dart
    - annotation SerializersFor
