#!/bin/bash --
# Copyright (c) 2016, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

cd built_value \
    && pub get \
    && pub run test \
    && cd ../built_value_generator \
    && pub get \
    && dart tool/build.dart \
    && pub run test \
    && cd ../end_to_end_test \
    && pub get \
    && dart tool/build.dart \
    && pub run test \
    && cd ../benchmark \
    && pub get \
    && dart tool/build.dart \
    && pub run test \
    && cd ../example \
    && pub get \
    && dart tool/build.dart \
    && pub run test \
    && cd ../chat_example \
    && pub get \
    && dart tool/build.dart \
    && pub run test
