name: Build

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: dev
      - name: Run Presubmits
        run: tool/presubmit
